# This is an example configuration file for the Spello Consulting utility library

# Just an example section to show how to set up a section
AmberAPI:
  APIKey: ""
  BaseUrl: https://api.amber.com.au/v1
  Timeout: 16

# Settings for oen or more Shelly smart switches. See documentation for more details.
ShellyDevices:
  AllowDebugLogging: True
  ResponseTimeout: 3
  RetryCount: 1
  RetryDelay: 2
  PingAllowed: True
  # Enable or disable the webhook listener
  WebhooksEnabled: True
  # IP to listen for webhooks on. This should be the IP address of the machine running the app. Defaults to 0.0.0.0
  WebhookHost: 192.168.86.32
  # Port to listen for webhooks on. Defaults to 8787.
  WebhookPort: 8787
  # The URI path that webhooks will post to.
  WebhookPath: /shelly/webhook  
  # The webhooks to install by default
  DefaultWebhooks:
    Inputs:
      - input.toggle_on
      - input.toggle_off
      - input.button_push
    Outputs:
      - switch.on
      - switch.off
  Devices:
    - Name: Spello Test A
      Model: Shelly2PMG3
      Hostname: 192.168.86.39
      Simulate: True
      Inputs: 
        - Name: "Spello Pool I1"
        - Name: "Spello Pool I2"
      Outputs:
        - Name: "Spello Pool Switch"
        - Name: "Spello Pool Switch Spare"
      Meters:
        - Name: "Spello Pool Meter"
          MockRate: 0.5
        - Name: "Spello Pool Meter Spare"
    - Name: Spello Dev
      Model: Shelly2PMG3
      Hostname: 192.168.86.33
      Simulate: True
      Inputs:
        - Name: "Spello Dev I1"
          Webhooks: True
        - Name: "Spello Dev I2"
      Outputs:
        - Name: "Spello Dev S1"
          Group: Patio
        - Name: "Spello Dev S2"
          Group: Patio

Files:
  LogfileName: test_logfile.log
  LogfileMaxLines: 501
  LogProcessID: True
  LogThreadID: True
  LogfileVerbosity: all
  ConsoleVerbosity: summary

# Enter your settings here if you want to be emailed when there's a critical error 
Email:
  EnableEmail: True
  SendEmailsTo: nick@elseyworld.com
  SMTPServer: smtp.gmail.com
  SMTPPort: 587
  SMTPUsername: nick@elseyworld.com
  SMTPPassword: ntgl vvhg igpd irwe
  SubjectPrefix: 
